name: Scheduled Job

on:
  schedule:
    - cron: "0 12 */10 * *"
    # - cron: "0 0,6,12,18 * * *"
    # - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your dependencies, if any

      - name: Run script
        run: python ytscript.py  # Replace with the actual name of your Python script
